-- 코드를 입력하세요
SELECT
    FOOD_TYPE,
    REST_ID,
    REST_NAME,
    FAVORITES 
-- 음식 종류별로 즐겨찾기가 가장 많은 식당 
FROM REST_INFO
    WHERE (FAVORITES,FOOD_TYPE) IN 
    (SELECT MAX(FAVORITES),FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC; 
