-- 코드를 입력하세요
SELECT
ii.INGREDIENT_TYPE AS INGREDIENT_TYPE,
SUM(fh.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF fh
JOIN ICECREAM_INFO ii ON ii.FLAVOR = fh.FLAVOR
GROUP BY ii.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;